steps:
  - name: checkout
    image: alpine/git
    commands:
      - git status
      - git log --oneline -5

  - name: lint
    image: golangci/golangci-lint:latest
    commands:
      - golangci-lint run ./...

  - name: test
    image: golang:1.24-alpine
    commands:
      - go test ./...

  - name: docker
    image: plugins/docker
    settings:
      repo: saiharsha-plivo/woodpecker-app
      tags: latest
      dockerfile: Dockerfile
    when:
      branch: main
      event: push
